### ISSUE TITLE
epg.html and mag.html remain blank

### ISSUE THREAD

**Issue by SevenW** [polini/TvheadendMobileUI#11]
The epg  page remain blank. The mag page displays an empty table and some buttons. In google chrome debug console no excpetions occur. The mobile page is working however.
I am working with a fresh build of tvheadend.

**Comment by SevenW** [comment]
it has something to do with a rewrite of webui.
channels does not exist anymore, and replaced with something with idnodes.
I have not yet found a nice guide on how to use the (new) api

**Comment by FutureCow** [comment]
Because of the new API, this nice UI is not fully working anymore. Do you have plans to update to the newer API's?

**Comment by polini** [comment]
Should now be fixed in the new branch tvheadend-4.0.

Please try
