### ISSUE TITLE
EPG does not show all channels

### ISSUE THREAD

**Issue by belliash** [polini/TvheadendMobileUI#15]
In desktop website, I can browse EPG for all channels (over 100). But with this mobile UI, only 50 are listed and they are not first 50. Looks like its randomizing which channel to show, however after refreshing the channel list is constant.

What happens to other channels and why aren't they showed?
This happens on both timeline & listing.

**Comment by polini** [comment]
Fixed in commit 883f2ff7a0ef68b6780510c04ea00534149d650d
