### ISSUE TITLE
Show channel name instead of logo

### ISSUE THREAD

**Issue by scho0ck** [polini/TvheadendMobileUI#16]
Hi,

Is it possible to show the channel name if no logo is available or show the channel name in general?

I have the problem that I don't have a logo for most channels so the EPG won't show any name or whatsoever?

Thanks

**Comment by polini** [comment]
Which view do you mean? Timeline view?

**Comment by scho0ck** [comment]
Yes the timeline view

**Comment by polini** [comment]
should be fixed by commit  9a3efc6
