### ISSUE TITLE
Timeline ignore channeltag selection

### ISSUE THREAD

**Issue by stepborc** [polini/TvheadendMobileUI#17]
While using the timeline view (on the "tvheadene-4.0" branch) you will see in the first line all events from all the channels that are not part of the channeltag selection.

That means: if you select all "TV Channels" you'll get a timeline with all tv channels plus the radio channels in the first timeline line.

It's possible to solve this problem. In the tvh_epg.js file there is the function 'readChannels'. Add a global array to the inner for-loop and add all the channels to it.

Then add an if-clause to the function 'readEpg' to decide if the channel is in the list or not. Depending on the result, you'll create the timeline view.

**Comment by polini** [comment]
fixed with ba48e12
