### ISSUE TITLE
Enrich recording log

### ISSUE THREAD

**Issue by gborri** [polini/TvheadendMobileUI#2]
Would be useful if there willbe episode info in recording tab: upcoming, failed, etc.

**Comment by polini** [comment]
Episode info is now shown. Please test it, as I haven't got episode infos in my epg.

**Comment by gborri** [comment]
this evening i will try and let you know.

thanks
Giovanni

**Comment by gborri** [comment]
probably i haven't express myself in the right way.
You have add episode and season in the EPG near the title, but in te epg was already there.
I meant to add episode and season, like the EPG under the title, on the upcoming recording tab; should be usefull also in the other tab; failed and  finished recording.

thanks

**Comment by polini** [comment]
There was a typo, please try again.

Do you really mean the episode info (see Web-UI column "Episode") or the subtitle of the EPG (Web-UI column "SubTitle"), which could also contain the episode information (depending on broadcaster / XML-TV source)?

**Comment by gborri** [comment]
Ok.

Now finished recording. Tab is working again.

I have seen that you have changed the behaviour of finished recording tab.

What I have seen before your last update was:
title season episode/subtitle ( depending in what you have coded, my xmltv
set subtitle equal to episode )
date of recording, duration of recording - season episode/subtitle- channel.

 Now I see:

title season episode
date duration channel

Probably the best would be:

title - subtitle
Date duration - season x episode y - channel

Thanks
Giovanni

On 11/feb/2013, at 23:39, polini notifications@github.com wrote:

There was a typo, please try again.

Do you really mean the episode info (see Web-UI column "Episode") or the
subtitle of the EPG (Web-UI column "SubTitle"), which could also contain
the episode information (depending on broadcaster / XML-TV source)?

—
Reply to this email directly or view it on
GitHubhttps://github.com/polini/TvheadendMobileUI/issues/2#issuecomment-13407663.

**Comment by polini** [comment]
At the moment it is not possible to include the subtitle for recordings, as Tvheadend doesn't return the subtitle for recordings. See the Web-UI, there's also no subtitle column in the recording tabs.

**Comment by gborri** [comment]
ok, you are right.

for the moment, if you agree, we can make like this, for upcaming, failed and finished:
Title
day and time of recording - Season x Episode y - Channel

as it is in the epg section of the channel.

**Comment by polini** [comment]
The current implementation is consequent:
- The episode info is directly behind the title in gray italic letters. (in currently playing, epg list and recording lists)
- The subtitle is under the title (in currently playing and epg list, but missing in recording lists)

Please note that, there were two recent commits with fixes for displaying episode info (bcac52f2c2 and 176fd38fe8)

**Comment by gborri** [comment]
i have seen it.

follow my consideration:
1. EPG - List of channel (ex. All Channel)
   - from what i can desume we have:
     - 'title''Season/Episode' without a space --> i will prefer
       'Title' - 'Subtitle' ('-' only if subtitle is present)
     - under title Subtitle--> i will prefer Season/Episode
   - EPG - timetable for channel (Ex. Rai 2)
   - i will prefer as for se previous section:
     - 'Title' - Subtitle ('-' only if subtitle is present)
     - Time of strt - Season/Episode
   - EPG - Stream detail
   - as it is todai is fine; my understandi is:
     - Title
     - Subtitle
     - ather structured info
   - DVR TAB (Upcoming, Finieshed,failed recording
   -  'Title' - 'Subtitle' (Subtitle when will be available)
   - 'date' 'time' (duration) - Season/Episode - Channel

this my wishes, becouse i think that is more readable.

thanks
Giovanni

**Comment by polini** [comment]
In my opinion the subtitle should be below the title (as the name "subtitle" states)...

I implemented two different layouts, so the user can switch the layout. The default is the layout suggested by you, so I think, this issue can be closed.

**Comment by gborri** [comment]
thanks.

you can close IT.
this evening i'll try your change and let you know.

Giovanni

**Comment by gborri** [comment]
Thanks Polini, i like it.

Thanks you also for the hard word to make it work. Do you think it's
possible to ask Adam to merge it in the master branch?

Giovanni

On 13/feb/2013, at 12:43, Giovanni Borri giovanni.borri@gmail.com wrote:

thanks.

you can close IT.
this evening i'll try your change and let you know.

Giovanni
