### ISSUE TITLE
Show epg by time

### ISSUE THREAD

**Issue by polini** [polini/TvheadendMobileUI#4]
E.g. Today at 8pm, 10pm

**Comment by polini** [comment]
It's not very performant, so this won't be fixed at the moment

**Comment by gborri** [comment]
I won't open an issue, but i would like tell you that if i open timeline either from Web-UI or Mobile-UI the channels icon overlap the text of the current show.

**Comment by gborri** [comment]
sorry i forgot: the text is on three line the first and the second are shown, the third line is shown horizontally half of because is cut.
