### ISSUE TITLE
episode info and upcoming recording

### ISSUE THREAD

**Issue by gborri** [polini/TvheadendMobileUI#5]
probably you have introduced some regression with the modify you have made.
I've tried your modification and this is what i have seen.

I started an autorec schedule and tvheadend will schedule all the tv show found on epg (i see it on web versione. when i try to access upcoming recording from mobile there's no recording scheduled.

the only things that i see is Loading...

**Comment by polini** [comment]
I cant reproduce the issue. Can you please retry and give me the exact steps to reproduce it?

**Comment by gborri** [comment]
Simple.

Enable autorec rule (you sound have it created before via web GUI) and then
try to see what's on recording tab.

Giovanni

On 06/feb/2013, at 21:43, polini notifications@github.com wrote:

I cant reproduce the issue. Can you please retry and give me the exact
steps to reproduce it?

—
Reply to this email directly or view it on
GitHubhttps://github.com/polini/TvheadendMobileUI/issues/5#issuecomment-13203998.

**Comment by polini** [comment]
which browser do you use? safari? still can not reproduce this issue.

can you perhaps try it in desktop browser and look if there is an error in the javascript console?

**Comment by gborri** [comment]
i'm using safari.
This evening i will try with a standard web browser.
But the problem wasn't there before you make the last commit.

thanks
Giovanni

**Comment by gborri** [comment]
before last update i have realized that the problem was related to the number of entry in Upcaming recording.
if there was 1 entry it was shown, if more than 1 nothing was visible.
Now after your change i can't see neither one entry.

Giovanni

**Comment by gborri** [comment]
you can close it.

thanks
Giovanni
