### ISSUE TITLE
clear button on search

### ISSUE THREAD

**Issue by gborri** [polini/TvheadendMobileUI#7]
Hello Polini,

could be useful to have a 'x' button on the end of the search box in order to clear what have been writed on the box (iphone like stile). today for clearing the box you have to clear all the character one by one.

thanks
Giovanni

**Comment by polini** [comment]
should be fixed now

**Comment by gborri** [comment]
Thanks
Giovanni

On 09/mar/2013, at 17:03, polini notifications@github.com wrote:

should be fixed now

—
Reply to this email directly or view it on
GitHubhttps://github.com/polini/TvheadendMobileUI/issues/7#issuecomment-14665420
.
